language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql RAILS_ENV=test
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database leada_test' -U postgres
script:
  - bundle exec rake --trace db:migrate
  - bundle exec rspec spec

