language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - cp config/database.travis.yml config/datebase.yml
  - psql -c 'create database leada_test' -U postgres
