language: ruby
rvm:
  - 2.1.2
env:
  - DB=postgresql
script:
  - RAILS_ENV=test rake --trace db:migrate
  - rspec .
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database leada_test' -U postgres
